## Defining a Panda series

In [1]:
import pandas as pd
import numpy as np

In [2]:
s1 = pd.Series([10, 20, 30, 40, 50])

In [3]:
s1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
s2 = pd.Series([1.2, 2.3, 4.5])
s2

0    1.2
1    2.3
2    4.5
dtype: float64

In [5]:
s3 = pd.Series([1,2,3,4,5], index=['a', 'b', 'c', 'd', 'e'])
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
s1[2]

np.int64(30)

In [7]:
s4 = s3 + 5
s4

a     6
b     7
c     8
d     9
e    10
dtype: int64

## Filtering

In [8]:
s2 = s1[s1>20]
s2

2    30
3    40
4    50
dtype: int64

## Numpy and Pandas together

In [9]:
arr = np.array([10,20,30,40,50])
print(arr)
s = pd.Series(arr)
s

[10 20 30 40 50]

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
t = np.sqrt(s)
print(t)

0    3.162278
1    4.472136
2    5.477226
3    6.324555
4    7.071068
dtype: float64

In [11]:
indexes = ['a', 'b', 'c', 'd']
arrs = [1,2,3,4]

s = pd.Series(arrs, indexes)
s

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
s.size

4

### Average of elements

In [13]:
s1 = pd.Series([10,20,30,40,50])
s1.mean()

np.float64(30.0)

In [14]:
s1.max()

50

In [15]:
s1.min()

10

In [16]:
print(s1.sort_values(ascending=True))
print(s1) # Not changes, use s1 = s1.sort_values() to update

0    10
1    20
2    30
3    40
4    50
dtype: int64
0    10
1    20
2    30
3    40
4    50
dtype: int64

## Removing duplicates

In [17]:
s1 = pd.Series([1,2,3,4,5,2])
print(s1.unique())
s1 = pd.Series(s1.unique())
print(s1)
print(s1.nunique())

[1 2 3 4 5]
0    1
1    2
2    3
3    4
4    5
dtype: int64
5

## Get statistics of a series

In [18]:
s1.describe()

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64

## Creating a dataframe

In [19]:
df = pd.DataFrame(s1)
df

   0
0  1
1  2
2  3
3  4
4  5

### Create a dataframe using dictionary

In [20]:
names = ["Virat", "Rohit"]
teams = ["RCB", "MI"]
_dict = {"Name": names, "Team": teams}

df = pd.DataFrame(_dict)
df

    Name Team
0  Virat  RCB
1  Rohit   MI

### Using list

In [21]:
l = [{'name': 'Virat', 'team': 'RCB'},
     {'name': "Rohit", 'team': 'MI'}]
df = pd.DataFrame(l)
df

    name team
0  Virat  RCB
1  Rohit   MI

In [22]:
for (ind, val) in df.iterrows():
    print(f"Row index: {ind}")
    print(f"Row value: {val}")
    print("\n")

Row index: 0
Row value: name    Virat
team      RCB
Name: 0, dtype: object


Row index: 1
Row value: name    Rohit
team       MI
Name: 1, dtype: object

In [23]:
for (ind, val) in df.items():
    print(f"Row index: {ind}")
    print(f"Row value: {val}")
    print("\n")

Row index: name
Row value: 0    Virat
1    Rohit
Name: name, dtype: object


Row index: team
Row value: 0    RCB
1     MI
Name: team, dtype: object

### Drop column/Row

In [27]:
s = pd.Series([10,15,18,22])
df = pd.DataFrame(s)
df.columns = ['Col1']
df['Col2'] = 20
df['Col3'] = df['Col2'] + df['Col1']
df

   Col1  Col2  Col3
0    10    20    30
1    15    20    35
2    18    20    38
3    22    20    42

In [29]:
df1 = df.drop(index=[1], axis=0)
df1

   Col1  Col2  Col3
0    10    20    30
2    18    20    38
3    22    20    42

### Boolean indexing

In [30]:
_dict = {'Name': ['Saurabh', 'Akash', 'Vikas'],
         'Age': [50, 34, 29]}

df = pd.DataFrame(_dict, index = [True, True, False])
df

          Name  Age
True   Saurabh   50
True     Akash   34
False    Vikas   29

In [31]:
print(df.loc[True])

         Name  Age
True  Saurabh   50
True    Akash   34

### DataFrame.loc

In [32]:
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                "B":[7, 2, 54, 3, None],
                "C":[20, 16, 11, 3, 8],
                "D":[14, 3, None, 2, 6]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the DataFrame
print("Original DataFrame:")
print(df)

# Corrected column names ('A' and 'D') in the result
result = df.loc[:, ['A', 'D']]

# Print the result
print("\nSelected Columns 'A' and 'D':")
print(result)

Original DataFrame:
          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

Selected Columns 'A' and 'D':
          A     D
Row_1  12.0  14.0
Row_2   4.0   3.0
Row_3   5.0   NaN
Row_4   NaN   2.0
Row_5   1.0   6.0

In [33]:
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({"A": [12, 4, 5, None, 1],
                   "B": [7, 2, 54, 3, None],
                   "C": [20, 16, 11, 3, 8],
                   "D": [14, 3, None, 2, 6]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the original DataFrame
print("Original DataFrame:")
print(df)

# Select Rows Between 'Row_2' and 'Row_4'
selected_rows = df.loc['Row_2':'Row_4']
print("\nSelected Rows:")
print(selected_rows)

# Select Columns 'B' through 'D'
selected_columns = df.loc[:, 'B':'D']
print("\nSelected Columns:")
print(selected_columns)

Original DataFrame:
          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

Selected Rows:
         A     B   C    D
Row_2  4.0   2.0  16  3.0
Row_3  5.0  54.0  11  NaN
Row_4  NaN   3.0   3  2.0

Selected Columns:
          B   C     D
Row_1   7.0  20  14.0
Row_2   2.0  16   3.0
Row_3  54.0  11   NaN
Row_4   3.0   3   2.0
Row_5   NaN   8   6.0

### DataFrame.concat()

In [35]:
dict1 = {'id': [1,2,3],
         'Name': ['Saurabh', 'Akash', 'Vikas']}
df1= pd.DataFrame(dict1)

dict2 = {'id': [5],
         'Name': ['Random']}
df2 = pd.DataFrame(dict2)

df3 = pd.concat([df1, df2])
df3

   id     Name
0   1  Saurabh
1   2    Akash
2   3    Vikas
0   5   Random